// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeedProject_V6.Models;

namespace SeedProject_V6.Migrations
{
    [DbContext(typeof(Seed_DBContext))]
    partial class Seed_Project_DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SeedProject_V6.Models.SeedProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<string>("ProductName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("productName");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int")
                        .HasColumnName("vendorId");

                    b.HasKey("ProductId")
                        .HasName("PK_Product");

                    b.ToTable("seed_Product");
                });

            modelBuilder.Entity("SeedProject_V6.Models.SeedProductInfo", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("date")
                        .HasColumnName("dateAdded");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("productDescription");

                    b.Property<string>("ProductImg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("productImg");

                    b.Property<string>("ProductPrice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("productPrice");

                    b.Property<double?>("ProductRating")
                        .HasColumnType("float")
                        .HasColumnName("productRating");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("int")
                        .HasColumnName("ratingCount");

                    b.HasKey("ProductId")
                        .HasName("PK_Seed_Products");

                    b.ToTable("seed_ProductInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
